
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author egeba
 */
public class Web extends javax.swing.JFrame
{

    /**
     * Creates new form Web
     */
    public Web()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tiklaButton = new javax.swing.JButton();
        yazi_alani = new javax.swing.JTextField();
        rastgelenot_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tiklaButton.setBackground(new java.awt.Color(255, 0, 0));
        tiklaButton.setText("Tıkla");
        tiklaButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tiklaButtonActionPerformed(evt);
            }
        });

        rastgelenot_button.setText("Rastgele Notlar");
        rastgelenot_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rastgelenot_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(yazi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tiklaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(rastgelenot_button)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(yazi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiklaButton)
                    .addComponent(rastgelenot_button))
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiklaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tiklaButtonActionPerformed
    {//GEN-HEADEREND:event_tiklaButtonActionPerformed
      String internet_adresi = yazi_alani.getText();// textte yazanı verir bana
        Desktop d = Desktop.getDesktop(); // masaüstümüze erişir
     
        try
        {
            //ve tarayıcımız(browserımıza kullanmamıza olanak sağlar
            d.browse(new URI (internet_adresi));
        } catch (IOException ex) // Io exception i nolur nolmaz yakalasın diye
        {
            Logger.getLogger(Web.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex)
        {
            Logger.getLogger(Web.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_tiklaButtonActionPerformed

    private void rastgelenot_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rastgelenot_buttonActionPerformed
    {//GEN-HEADEREND:event_rastgelenot_buttonActionPerformed
      
           File file = new File("C:\\Users\\egeba\\Desktop\\Rastgele Notlar.txt");// tam yol kopyala
        
        //first check if Desktop is supported by Platform or not
        if(!Desktop.isDesktopSupported()){
            System.out.println("Desktop is not supported");
            return;
        }
        
        Desktop desktop = Desktop.getDesktop();
        //--Dosya varmı yok mu ?
          if(file.exists()) try {
            desktop.open(file);
          } catch (IOException ex) {
             Logger.getLogger(Web.class.getName()).log(Level.SEVERE, null, ex);
          }
        
        //let's try to open PDF file
        file =  new File("C:\\Users\\egeba\\Desktop\\Rastgele Notlar.txt");
        if(file.exists()) try {
            desktop.open(file);
           } catch (IOException ex) {
               Logger.getLogger(Web.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_rastgelenot_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Web.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Web.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Web.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Web.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Web().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton rastgelenot_button;
    private javax.swing.JButton tiklaButton;
    private javax.swing.JTextField yazi_alani;
    // End of variables declaration//GEN-END:variables
}
