
import java.awt.Color;
import java.awt.Graphics;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author egeba
 */
public class HesapMakinesiSwing extends javax.swing.JFrame
{
    
    @Override
    public void paint(Graphics draw){
      //Here you can perform any drawing like an oval...
    
       
      getContentPane().setBackground(new Color(70,220,120));
    }

    
    class gecersizSayi extends Exception
    {

        @Override
        public void printStackTrace()
        {
            sonuc.setText("Geçersiz Sayılar...");
        }

    }
    private Scanner scanner = new Scanner(System.in);

    /**
     * Creates new form HesapMakinesiSwing
     */
    public HesapMakinesiSwing()
    {
        initComponents();
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        toplama = new javax.swing.JButton();
        cikarma = new javax.swing.JButton();
        carpma = new javax.swing.JButton();
        bolme = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        birinciSayi = new javax.swing.JTextField();
        ikinciSayi = new javax.swing.JTextField();
        sonuc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toplama.setText("+");
        toplama.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toplamaActionPerformed(evt);
            }
        });

        cikarma.setText("-");
        cikarma.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cikarmaActionPerformed(evt);
            }
        });

        carpma.setText("x");
        carpma.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                carpmaActionPerformed(evt);
            }
        });

        bolme.setText("/");
        bolme.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bolmeActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Birinci Sayi : ");

        jLabel2.setText("İkinci Sayi  :");

        jLabel3.setText("Sonuç       :");

        sonuc.setEditable(false);
        sonuc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sonucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(toplama)
                    .addComponent(carpma))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bolme)
                    .addComponent(cikarma)
                    .addComponent(ikinciSayi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birinciSayi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(birinciSayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ikinciSayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cikarma)
                    .addComponent(toplama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carpma)
                    .addComponent(bolme))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sonucActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sonucActionPerformed
    {//GEN-HEADEREND:event_sonucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonucActionPerformed

    private void toplamaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toplamaActionPerformed
    {//GEN-HEADEREND:event_toplamaActionPerformed

        int birinci = Integer.valueOf(birinciSayi.getText()); // birinciSayi textinden stringi alıp int e çevirdik
        int ikinci = Integer.valueOf(ikinciSayi.getText()); // ikinciSayi textinden Stringi alıp int 'e çevirdik
  try
        {
            if (birinci > 10000 && ikinci > 10000)
            {
                throw new gecersizSayi();

            }

        } catch (gecersizSayi ex)
        {
            ex.printStackTrace();
            return;
        }
        sonuc.setText(String.valueOf(birinci + ikinci));

    }//GEN-LAST:event_toplamaActionPerformed

    private void cikarmaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cikarmaActionPerformed
    {//GEN-HEADEREND:event_cikarmaActionPerformed
        int birinci = Integer.valueOf(birinciSayi.getText()); // birinciSayi textinden stringi alıp int e çevirdik
        int ikinci = Integer.valueOf(ikinciSayi.getText()); // ikinciSayi textinden Stringi alıp int 'e çevirdik
  try
        {
            if (birinci > 10000 && ikinci > 10000)
            {
                throw new gecersizSayi();

            }

        } catch (gecersizSayi ex)
        {
            ex.printStackTrace();
            return;
        }
        sonuc.setText(String.valueOf(birinci - ikinci));
    }//GEN-LAST:event_cikarmaActionPerformed

    private void carpmaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_carpmaActionPerformed
    {//GEN-HEADEREND:event_carpmaActionPerformed
        int birinci = Integer.valueOf(birinciSayi.getText()); // birinciSayi textinden stringi alıp int e çevirdik

        int ikinci = Integer.valueOf(ikinciSayi.getText()); // ikinciSayi textinden Stringi alıp int 'e çevirdik
        try
        {
            if (birinci > 10000 && ikinci > 10000)
            {
                throw new gecersizSayi();

            }

        } catch (gecersizSayi ex)
        {
            ex.printStackTrace();
            return;
        }

        sonuc.setText(String.valueOf(birinci * ikinci));
    }//GEN-LAST:event_carpmaActionPerformed

    private void bolmeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bolmeActionPerformed
    {//GEN-HEADEREND:event_bolmeActionPerformed
        int birinci = Integer.valueOf(birinciSayi.getText()); // birinciSayi textinden stringi alıp int e çevirdik
        int ikinci = Integer.valueOf(ikinciSayi.getText()); // ikinciSayi textinden Stringi alıp int 'e çevirdik
        try
        {
            if (birinci > 10000 && ikinci > 10000)
            {
                throw new gecersizSayi();

            }

        } catch (gecersizSayi ex)
        {
            ex.printStackTrace();
            return;
        }

        

        sonuc.setText(String.valueOf((double) birinci / ikinci));
    }//GEN-LAST:event_bolmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HesapMakinesiSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HesapMakinesiSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HesapMakinesiSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HesapMakinesiSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                
                new HesapMakinesiSwing().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birinciSayi;
    private javax.swing.JButton bolme;
    private javax.swing.JButton carpma;
    private javax.swing.JButton cikarma;
    private javax.swing.JTextField ikinciSayi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField sonuc;
    private javax.swing.JButton toplama;
    // End of variables declaration//GEN-END:variables
}
