
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author egeba
 */
public class StokUygulamasi extends javax.swing.JFrame
{

    /**
     * Creates new form StokUygulamasi
     */
    public StokUygulamasi()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_urunisim = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox();
        tf_fiyat = new javax.swing.JTextField();
        mesaj_alani = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        ekle_buttonu = new javax.swing.JButton();
        guncelle_butonu = new javax.swing.JButton();
        sil_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("        STOK");

        jLabel1.setText("Ürün İsmi:");

        jLabel2.setText("Kategori:");

        jLabel3.setText("Fiyat:");

        tf_urunisim.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tf_urunisimActionPerformed(evt);
            }
        });

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yemek", "Elektronik", "Kültür Sanat" }));

        tf_fiyat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tf_fiyatActionPerformed(evt);
            }
        });

        mesaj_alani.setForeground(new java.awt.Color(255, 0, 0));

        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Ürün ismi", "Kategori", "Fiyat"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);

        ekle_buttonu.setText("Ürün Ekle ");
        ekle_buttonu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ekle_buttonuActionPerformed(evt);
            }
        });

        guncelle_butonu.setText("Ürün Güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guncelle_butonuActionPerformed(evt);
            }
        });

        sil_button.setText("Ürün Sil");
        sil_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sil_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel3)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_urunisim)
                            .addComponent(cb_kategori, 0, 160, Short.MAX_VALUE)
                            .addComponent(tf_fiyat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ekle_buttonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guncelle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(sil_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(mesaj_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_urunisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle_buttonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle_butonu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(sil_button)))
                .addGap(30, 30, 30)
                .addComponent(mesaj_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_urunisimActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tf_urunisimActionPerformed
    {//GEN-HEADEREND:event_tf_urunisimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_urunisimActionPerformed

    private void tf_fiyatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tf_fiyatActionPerformed
    {//GEN-HEADEREND:event_tf_fiyatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fiyatActionPerformed

    private void ekle_buttonuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ekle_buttonuActionPerformed
    {//GEN-HEADEREND:event_ekle_buttonuActionPerformed
        mesaj_alani.setText(""); // mesaj alanını ilk başta temizliyorum...

        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        if (tf_urunisim.getText().trim().equals(""))
        {
            mesaj_alani.setForeground(Color.RED);
            mesaj_alani.setText("Ürün İsmi alanı boş bırakılamaz !");
        }
        else
        {

            Object[] eklenecek =
            {
                tf_urunisim.getText(), cb_kategori.getSelectedItem().toString(), tf_fiyat.getText()
            };

            model.addRow(eklenecek); // row ekle satır ekle ekleneceği ekle dedik
            mesaj_alani.setForeground(Color.GREEN);
            mesaj_alani.setText("Ürün başarılı bir şekilde eklendi ! ");
            tf_urunisim.setText("");
            tf_fiyat.setText("");

        }

    }//GEN-LAST:event_ekle_buttonuActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guncelle_butonuActionPerformed
    {//GEN-HEADEREND:event_guncelle_butonuActionPerformed

        mesaj_alani.setText("");
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        int secili_row = urun_tablosu.getSelectedRow();
        if (secili_row == -1)
        {
            if (urun_tablosu.getRowCount() == 0)
            {

                mesaj_alani.setForeground(Color.BLUE);

                mesaj_alani.setText("Ürün tablosunda ürün bulunmamaktadır !");

            }
            else
            {
                mesaj_alani.setForeground(Color.BLUE);

                mesaj_alani.setText("Lütfen güncellenecek bir ürün seçiniz...");
            }

        }
        else
        {

            model.setValueAt(tf_urunisim.getText(), secili_row, 0);
            model.setValueAt(cb_kategori.getSelectedItem().toString(), secili_row, 1);
            model.setValueAt(tf_fiyat.getText(), secili_row, 2);

            mesaj_alani.setForeground(Color.GREEN);
            mesaj_alani.setText("Ürün Başarıyla Güncellendi !!!");
            tf_urunisim.setText("");
            tf_fiyat.setText("");

        }


    }//GEN-LAST:event_guncelle_butonuActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_urun_tablosuMouseClicked
    {//GEN-HEADEREND:event_urun_tablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        int secili_row = urun_tablosu.getSelectedRow();

        tf_urunisim.setText(model.getValueAt(secili_row, 0).toString());
        cb_kategori.setSelectedItem(model.getValueAt(secili_row, 1).toString());
        tf_fiyat.setText(model.getValueAt(secili_row, 2).toString());


    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void sil_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sil_buttonActionPerformed
    {//GEN-HEADEREND:event_sil_buttonActionPerformed
        mesaj_alani.setText("");
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        
        int secili_row=  urun_tablosu.getSelectedRow();
        if(secili_row == -1)
        {
            if(urun_tablosu.getRowCount() == 0){
                                 mesaj_alani.setForeground(Color.BLUE);

                mesaj_alani.setText("Ürün tablosunda ürün bulunmamaktadır !");

            }
            else
            {
                 mesaj_alani.setForeground(Color.BLUE);

                mesaj_alani.setText("Lütfen silinecek bir ürün seçiniz...");
               
                
            }
        }
        else{
            model.removeRow(secili_row);
            mesaj_alani.setForeground(Color.ORANGE);
            mesaj_alani.setText("Ürün başarılı bir şekilde kaldırıldı !");
        }

        
    }//GEN-LAST:event_sil_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new StokUygulamasi().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_kategori;
    private javax.swing.JButton ekle_buttonu;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_alani;
    private javax.swing.JButton sil_button;
    private javax.swing.JTextField tf_fiyat;
    private javax.swing.JTextField tf_urunisim;
    private javax.swing.JTable urun_tablosu;
    // End of variables declaration//GEN-END:variables
}
