
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author egeba
 */
public class CheckBox extends javax.swing.JFrame
{
    
private Set<String> set =  new LinkedHashSet<String>();
   public void  labelDegistir(){
        
        String yazi ="Şu diller seçildi : ";
        for(String c: set){
            yazi += c + " ";
        }
        diller_alani.setText(yazi);
    }
    /**
     * Creates new form CheckBox
     */
    public CheckBox()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        python_check = new javax.swing.JCheckBox();
        php_chechk = new javax.swing.JCheckBox();
        java_chechk = new javax.swing.JCheckBox();
        gosterButton = new javax.swing.JButton();
        diller_alani = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("              Dil Seçimi");

        python_check.setText("Python");

        php_chechk.setText("Php");

        java_chechk.setText("Java");

        gosterButton.setText("Göster");
        gosterButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gosterButtonActionPerformed(evt);
            }
        });

        diller_alani.setText("Şu diller seçildi : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gosterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(python_check)
                            .addComponent(java_chechk)
                            .addComponent(php_chechk))))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(diller_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(java_chechk)
                .addGap(18, 18, 18)
                .addComponent(python_check)
                .addGap(18, 18, 18)
                .addComponent(php_chechk)
                .addGap(34, 34, 34)
                .addComponent(diller_alani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(gosterButton)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private void gosterButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gosterButtonActionPerformed
    {//GEN-HEADEREND:event_gosterButtonActionPerformed
      
      
        
        if(java_chechk.isSelected()){
            set.add("Java");
        }
        else
        {
            set.remove("Java");
        }
         if(python_check.isSelected()){
            set.add("Python");
        }
        else
        {
            set.remove("Python");
        }
          if(php_chechk.isSelected()){
            set.add("Php");
        }
        else
        {
            set.remove("Php");
        }
        labelDegistir();
          if(set.isEmpty())
        {
              diller_alani.setText("Lütfen bir seçim yapınız ...");
            JOptionPane.showMessageDialog(this, "Herhangi bir dil seçilmedi !");
          
            
        }
        
    }//GEN-LAST:event_gosterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diller_alani;
    private javax.swing.JButton gosterButton;
    private javax.swing.JCheckBox java_chechk;
    private javax.swing.JCheckBox php_chechk;
    private javax.swing.JCheckBox python_check;
    // End of variables declaration//GEN-END:variables
}
