
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author egeba
 */
public class CinsiyetSecimi extends javax.swing.JFrame
{
    private Set<String> set = new LinkedHashSet<String>();

    /**
     * Creates new form CinsiyetSecimi
     */
    public CinsiyetSecimi()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kadinRadio = new javax.swing.JRadioButton();
        erkekRadio = new javax.swing.JRadioButton();
        farketmezRadio = new javax.swing.JRadioButton();
        CinsiyetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinsiyet");
        setBackground(new java.awt.Color(0, 153, 153));

        buttonGroup1.add(kadinRadio);
        kadinRadio.setText("Kadın");
        kadinRadio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                kadinRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(erkekRadio);
        erkekRadio.setText("Erkek");

        buttonGroup1.add(farketmezRadio);
        farketmezRadio.setSelected(true);
        farketmezRadio.setText("Ne Fark Eder");

        CinsiyetButton.setBackground(new java.awt.Color(51, 51, 255));
        CinsiyetButton.setText("Cinsiyet Seç");
        CinsiyetButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CinsiyetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kadinRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(CinsiyetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(erkekRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(farketmezRadio)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kadinRadio)
                    .addComponent(erkekRadio)
                    .addComponent(farketmezRadio))
                .addGap(62, 62, 62)
                .addComponent(CinsiyetButton)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void cinsiyetGoster(){
        String message = "Cinsiyetiniz : ";
        for(String c : set){
            message +=c +" ";
        }
        JOptionPane.showMessageDialog(this, message);
    }
    private void CinsiyetButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CinsiyetButtonActionPerformed
    {//GEN-HEADEREND:event_CinsiyetButtonActionPerformed
       
        if(erkekRadio.isSelected()){
            set.add("Erkek");
            
        }
        else{
            set.remove("Erkek");
        }
        if(kadinRadio.isSelected()){
            set.add("Kadın");
            
        }
        else{
            set.remove("Kadın");
        }
        if(farketmezRadio.isSelected()){
            set.add("Ne Fark Eder");
            
        }
        else{
            set.remove("Ne Fark Eder");
        }
        cinsiyetGoster();
    }//GEN-LAST:event_CinsiyetButtonActionPerformed

    private void kadinRadioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kadinRadioActionPerformed
    {//GEN-HEADEREND:event_kadinRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kadinRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CinsiyetSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CinsiyetSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CinsiyetSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CinsiyetSecimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CinsiyetSecimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CinsiyetButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton erkekRadio;
    private javax.swing.JRadioButton farketmezRadio;
    private javax.swing.JRadioButton kadinRadio;
    // End of variables declaration//GEN-END:variables
}
