
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author egeba
 */
public class JlistIleKullanici extends javax.swing.JFrame
{
// varsayılan bir list model oluşturduk sonra da kullanıcı listesini fram başlar başlamaz set modelleyip belirledik o modelde
    DefaultListModel model = new DefaultListModel();

    
    /**
     * Creates new form JlistIleKullanici
     */
    
    public JlistIleKullanici()
    {
        initComponents();
        kullanici_listesi.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        kullanici_listesi = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();
        ekleButton = new javax.swing.JButton();
        silButton = new javax.swing.JButton();
        guncelleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanıcı Ekle-Sil");
        setBackground(new java.awt.Color(51, 51, 255));
        setBounds(new java.awt.Rectangle(400, 400, 0, 0));

        kullanici_listesi.setBackground(new java.awt.Color(153, 255, 153));
        jScrollPane1.setViewportView(kullanici_listesi);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kullanıcılar : ");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        ekleButton.setText("Kullanıcı Ekle");
        ekleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ekleButtonActionPerformed(evt);
            }
        });

        silButton.setText("Kullanıcı Sil");
        silButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                silButtonActionPerformed(evt);
            }
        });

        guncelleButton.setText("Kullanıcı Güncelle");
        guncelleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(ekleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(silButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ekleButton)
                .addGap(38, 38, 38)
                .addComponent(silButton)
                .addGap(42, 42, 42)
                .addComponent(guncelleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ekleButtonActionPerformed
    {//GEN-HEADEREND:event_ekleButtonActionPerformed
       mesaj_yazisi.setText("");
       String cevap = JOptionPane.showInputDialog("Kullanıcı ismi : ");
       if(cevap != null){
           if(cevap.trim().equals("")){
               mesaj_yazisi.setText("Boş bir kullanıcı ismi girdiniz !");
           }
           else{
               model.addElement(cevap);
               mesaj_yazisi.setText(cevap + " kullanıcısı başarılı bir şekilde  listeye eklendi");
               
           }
           
       }
       else{
           mesaj_yazisi.setText("İşlem iptal edildi !");
       }
        
        
    }//GEN-LAST:event_ekleButtonActionPerformed

    private void silButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_silButtonActionPerformed
    {//GEN-HEADEREND:event_silButtonActionPerformed
        mesaj_yazisi.setText("");
        int selected_index = kullanici_listesi.getSelectedIndex();
        if(selected_index == -1){
            if(model.getSize() == 0){
                mesaj_yazisi.setText("Kullanıcı listesi şu anda boş !");
            }
            else{
                mesaj_yazisi.setText("Lütfen silinecek bir kullanıcı seçiniz...");
            }
            
        }
        else{
            
            mesaj_yazisi.setText(model.get(selected_index) +" kullanıcısı başarılı bir şekilde silindi...");
            model.remove(selected_index);
        }
    }//GEN-LAST:event_silButtonActionPerformed

    private void guncelleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guncelleButtonActionPerformed
    {//GEN-HEADEREND:event_guncelleButtonActionPerformed
      
        mesaj_yazisi.setText("");
        int selected_index= kullanici_listesi.getSelectedIndex();
        if(selected_index == -1){
            if(model.getSize() == 0){
                mesaj_yazisi.setText("Kullanıcı listesi şu anda boş !");
            }
            else{
                mesaj_yazisi.setText("Lütfen güncellenecek bir kullanıcı seçiniz ...");
            }
            
        }
        else{
                   String cevap = JOptionPane.showInputDialog("Kullanıcı ismi : ");
                   model.remove(selected_index);
                    model.add(selected_index, cevap);
                    mesaj_yazisi.setText( cevap +" kullanıcısı başarılı bir şekilde güncellendi .");
            
        }
      //  String kullanici = JOptionPane.showInputDialog("Kullanıcı ismi : ");
      
        
       
    }//GEN-LAST:event_guncelleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JlistIleKullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JlistIleKullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JlistIleKullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JlistIleKullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JlistIleKullanici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekleButton;
    private javax.swing.JButton guncelleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList kullanici_listesi;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton silButton;
    // End of variables declaration//GEN-END:variables
}
